ALTER SESSION SET CURRENT_SCHEMA=SYSTEM;
-- Script para crear la tabla SEARCHES en Oracle XE
CREATE TABLE searches (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    search_id VARCHAR2(255) NOT NULL,
    hotel_id VARCHAR2(255) NOT NULL,
    check_in_date DATE NOT NULL,
    check_out_date DATE NOT NULL
);

-- Índices opcionales para mejorar búsquedas
CREATE INDEX idx_searches_search_id ON searches(search_id);
CREATE INDEX idx_searches_hotel_id ON searches(hotel_id);

-- Tabla para almacenar las edades de los huéspedes asociados a cada búsqueda
CREATE TABLE search_entity_ages (
    search_entity_id NUMBER(19,0) NOT NULL,
    ages NUMBER(10,0),
    CONSTRAINT PK_search_entity_ages PRIMARY KEY (search_entity_id, ages),
    CONSTRAINT FK_search_entity_ages_searches FOREIGN KEY (search_entity_id) REFERENCES searches(id) ON DELETE CASCADE
);