spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XE
    driver-class-name: oracle.jdbc.OracleDriver
    username: system
    password: apppassword
  h2:
    console:
      enabled: false
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'

app:
  kafka:
    topic: ${APP_KAFKA_TOPIC:hotel_availability_searches}

logging:
  level:
    root: INFO
    org.springframework: WARN
    org.apache.kafka: WARN
    org.hibernate: WARN
    com.zaxxer.hikari: WARN
    com.zaxxer.hikari.pool.HikariPool: ERROR
    com.zaxxer.hikari.HikariConfig: ERROR
    com.riu.challenge.hotel_availability_search: DEBUG


---
# Perfil de test para H2
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
